#debug: true
#trace=true
# 打开actuator 所有端点
management:
  endpoints:
    web:
      exposure:
        include: "*"
############################ web ############################
server:
  port: 2340
#  servlet:
#    context-path: /thd




spring:
  ############################ Db ############################
  datasource:
    # 数据库的url、登录名、密码和数据库名
    url: jdbc:mysql://127.0.0.1:3306/devil13th_pm?serverTimezone=Asia/Shanghai&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
    # 使用阿里的Druid连接池
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    # druid:
    # 连接池的配置信息
    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    # 打开PSCache，并且指定每个连接上PSCache的大小
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录 单位毫秒
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=50
    # 配置监控服务器
    stat-view-servlet:
      login-username: admin
      login-password: 123456
      reset-enable: false
      url-pattern: /druid/*
      # 添加IP白名单
      #allow:
      # 添加IP黑名单，当白名单和黑名单重复时，黑名单优先级更高
      #deny:
    web-stat-filter:
      # 添加过滤规则
      url-pattern: /*
      # 忽略过滤格式
      exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
  ############################ redis ############################

  ############################ swagger ############################
  swagger:
    enabled: true                                  # 是否启用swagger
    group:
      user-api:                                     # 用户组api，可以配置多个组
        group-name: 01.user-api                     # api组的名字，会在swagger-ui的api下拉列表中显示；组名前的序号，多个组可以排序；最好不要写中文
        title: 用户相关的操作                        # api组的标题，会在swagger-ui的标题处显示
        description: 用户相关的操作，包括用户登录登出  # api组的描述，会在swagger-ui的描述中显示
        #path-regex: /api/user/.*                    # 匹配到本组的api接口，匹配uri，可以用用正则表达式
        path-regex: /note/.*                    # 匹配到本组的api接口，匹配uri，可以用用正则表达式
        path-mapping: /                             # 匹配到的url在swagger中测试请求时加的url前缀
        version: 0.0.0                              # api版本
        license: 该文档仅限公司内部传阅               # 授权协议
        license-url: '#'                            # 授权协议地址
        terms-of-service-url:                       # 服务条款地址
        contact:                                    # 文档联系人
          name: 张三                                # 联系人名字
          email: zhangsan@team.com                  # 联系人邮箱
          url: http://www.team.com                  # 联系地址

mybatis:
  mapper-locations: classpath:com/thd/springboot/project/cgexample/mapper/*.xml #这里是mapper的配置文件
  # 这里是实体类的包 添加这个配置后就不用在mapper.xml配置文件中aliases了
  type-aliases-package: com.thd.springboot.project.cgexample.entity
  configuration:
    map-underscore-to-camel-case: true # 驼峰属性与数据库字段下划线自动转换
############################ Db - mybatis - 分页插件 ############################
pagehelper: ## mybatis分页
  ##数据库方言
  helperDialect: mysql
  ## 分页合理化参数，默认值为false。当该参数设置为 true 时，pageNum<=0 时会查询第一页， pageNum>pages（超过总数时），会查询最后一页。默认false 时，直接根据参数进行查询
  reasonable: true
  ## 是否支持通过 Mapper 接口参数来传递分页参数
  supportMethodsArguments: true
  params:
    count: countSql
############################ Db - mybatis-plugin - mybatis插件 ############################
#mybatis-plus:
#  configuration:
#    ## 打印日志
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

############################ 启用 shiro ############################
#shiro:
#  enable: true
#  redis-key-prefix:




############################ log ############################
logging:
  config: classpath:logback-spring.xml
  path: D:/deleteme/logbacks


